/* ------------------------------------------------------------------
   THE CORPUS — this is the product. Everything else is packaging.

   Cleanup applied to the source lists:
     - "hope driven dev" was duplicated verbatim inside the Enterprise
       Sarcasm file (lines 46-100). Split out into its own genre.
     - Removed 7 within-file duplicates from Enterprise Sarcasm and
       2 cross-file duplicates (kept in Developer Despair).
     - Stripped all ":check_mark: (Used on ...)" usage markers.
     - Normalised to Title Case with small-word rules; acronyms and
       lowercase identifiers (npm, node_modules) preserved.
     - Enterprise Sarcasm's five trailing subsections became their own
       genre, Catastrophe Theatre.
     - Occult Scrum reworked per "not weird enough": dropped the
       cliches, kept the good ones, added 26 stranger entries.
     - On-Call Horror split out of Developer Despair, which had grown
       to 109 and was carrying a distinct pager-dread cluster.
------------------------------------------------------------------ */
const GENRES = [
  { id:"despair", label:"Developer Despair", accent:"#1F4E9C", names:[
    "Works on My Machine",
    "Git Blame the Other Guy",
    "Not My Branch",
    "Works in Production",
    "Probably Not My Bug",
    "Wasn’t Me",
    "Ask the Previous Developer",
    "It Was Like That Already",
    "I Inherited This",
    "Who Wrote This?",
    "Future Me’s Problem",
    "Not Enough Context",
    "No Reproduction",
    "Cannot Reproduce",
    "Reproduces Locally",
    "Works in Staging",
    "Works Until It Doesn’t",
    "Just Don’t Touch It",
    "Do Not Refactor",
    "Please Don’t Look",
    "It’s Probably Caching",
    "Have You Tried Restarting?",
    "Must Be DNS",
    "Must Be a Race Condition",
    "It’s a Feature",
    "Legacy by Choice",
    "Technical Debt Enjoyer",
    "Debt Is Due",
    "Borrowed Time",
    "Held Together by Tests",
    "Held Together by Hope",
    "Held Together by Comments",
    "Comments Are the Documentation",
    "Documentation Is Somewhere",
    "README Is Lying",
    "The Tests Know Too Much",
    "Tests Are Optional",
    "CI Said Maybe",
    "Green Enough",
    "Pipeline Roulette",
    "Merge and Find Out",
    "Push First, Understand Later",
    "Commit and Forget",
    "Revert and Pretend",
    "Git Revert My Life",
    "Git Reset My Expectations",
    "Force Push of Despair",
    "Branching Out of Control",
    "Detached From Reality",
    "HEAD Is Not Found",
    "Lost in Git History",
    "Commit Archaeology",
    "Blame Driven Development",
    "Debugging by Astrology",
    "Debugging by Vibes",
    "Debugging by Screenshot",
    "Stack Overflow Archaeology",
    "Copy Paste Engineering",
    "Cargo Cult Coding",
    "Trial and Error™",
    "Error and More Error",
    "Exceptionally Unclear",
    "Null and Void",
    "Undefined Behavior, Defined Lifestyle",
    "Race Condition Enjoyer",
    "Concurrency Is a Social Problem",
    "The State Is Complicated",
    "State Management Crisis",
    "One More If",
    "Just One More Flag",
    "Temporary Permanent Fix",
    "Permanent Temporary Fix",
    "Quick Fix, Long Term Consequences",
    "Five Minute Refactor",
    "Small Change™",
    "Tiny Little Hotfix",
    "Harmless Change",
    "Nothing Could Go Wrong",
    "We’ll Understand It Later",
    "Future Us Can Deal With It",
    "Past Us Was an Idiot",
    "Past Me Did This",
    "I Blame Past Me",
    "Past Me Had Reasons",
    "Future Me Hates This",
    "Somebody Approved This",
    "Someone Signed Off",
    "It Passed Review",
    "LGTM, Unfortunately",
    "Approved Under Duress",
    "Peer Reviewed, Allegedly",
    "Tested in Spirit",
    "QA Has Been Notified",
    "Waiting for Reproduction",
    "Waiting for the Bug",
    "Waiting for Godot.js",
    "Production Has Feedback",
    "Users Are the Test Suite",
    "Customer Driven Debugging",
    "Live Debugging Experience",
    "Monday Morning Rollback",
    "Deploy First, Panic Later",
    "Git History Repeats Itself"
  ]},

  { id:"oncall", label:"On-Call Horror", accent:"#33307A", names:[
    "Three AM Deployment",
    "Escalation Pending",
    "Wake Up, It’s Production",
    "Who Has the Phone",
    "Weekend Incident",
    "Production Needs You",
    "On Call, On Sight",
    "Rotating the Suffering",
    "Severity: Weekend",
    "Blast Radius: Bedroom",
    "Five Nines, Zero Sleep",
    "Uptime at Any Cost",
    "Availability Has a Price",
    "SLA Versus REM",
    "Production Called",
    "Production Calls Again",
    "Production Has Your Number",
    "Production Knows Where You Sleep",
    "Weekend Availability Event",
    "Pinged by DevOps",
    "Not My Oncall Duty",
    "Page Duty Jump Scare",
    "Friday Deploy Survivor",
    "Incidentally, It’s an Incident",
    "Production Is My QA"
  ]},

  { id:"enterprise", label:"Enterprise Sarcasm", accent:"#A61F2B", names:[
    "Refactor and Pray",
    "Tactical Optimism",
    "Ship Happens",
    "Escalation Is a Feature",
    "Merge With Caution",
    "Agile-ish",
    "Retrospective Regret",
    "Plausible Deniability",
    "Overengineered for Safety",
    "Per My Last Email",
    "Re: Per My Last Email",
    "Stakeholder Delight",
    "Selective Transparency",
    "Cache Me Outside",
    "Ship It Anyway",
    "Optimistic Rollback",
    "Minimal Viable Apology",
    "Enterprise Grade Anxiety",
    "Refinement by Fire",
    "Unintended Consequences",
    "Human Interface Problem",
    "Scope Drift Initiative",
    "Hotfix Horizon",
    "Silent Breaking Change",
    "Rollback Ready",
    "Minor Major Release",
    "Soft Deadline",
    "Future Technical Debt",
    "Spec Drift",
    "Incident Driven Dev",
    "Untested Confidence",
    "Courageous Refactor",
    "Blameless Postmortem",
    "Architectural Regret",
    "Deadline Negotiation Phase",
    "Definition of “Done-ish”",
    "High Risk No Reward",
    "Just One More Thing",
    "Regression Roulette",
    "Release and Regret",
    "Unverified Assumptions",
    "Elegant Workaround",
    "Feature Creep Diplomacy",
    "Strategic Reprioritization",
    "Deadline Is a Suggestion",
    "Backward Compatibility Theater",
    "Continuous Partial Delivery",
    "Legacy of Tomorrow",
    "Technical Debt Jubilee",
    "Ship First, Document Never",
    "Requirements Are Fluid",
    "Slightly Deterministic",
    "Chaos Driven Development",
    "Roadmap to Nowhere",
    "Sustainable Panic",
    "Test in Production",
    "Compliance Adjacent",
    "Fail Forward Aggressively",
    "Stakeholder Alignment Ritual",
    "Soft Launch Into Darkness",
    "Beta Is the New Stable",
    "Zero Downtime (Probably)",
    "Mission Critical-ish",
    "Cloud Native Denial",
    "Scalable Confusion",
    "Automated Blame Pipeline",
    "KPI Exorcism",
    "Governance Theater",
    "Architecture Astronautics",
    "Incremental Catastrophe",
    "Proactive Damage Control",
    "Every User Has a Test System"
  ]},

  { id:"hope", label:"Hope Driven Dev", accent:"#1E6B4F", names:[
    "Optimism Under Review",
    "Hope Driven Development",
    "Confidence Pending",
    "Probably Fine",
    "Trust the Process",
    "Faith Based Deployment",
    "Strategic Optimism",
    "Hope as a Strategy",
    "Deferred Optimism",
    "Tentative Success",
    "Fingers Crossed",
    "Positive Outlook",
    "Managed Expectations",
    "Controlled Optimism",
    "Optimism Is Not a Bug",
    "Hopeful Regression",
    "Confidence in Progress",
    "Promisingly Unstable",
    "Potentially Fine",
    "Success by Thursday",
    "Future Looks Promising",
    "Eventually Correct",
    "Progress, Allegedly",
    "Almost Certain",
    "Low Confidence, High Hopes",
    "Operational Optimism",
    "Hopeful but Unverified",
    "Expected to Work",
    "Probability of Success",
    "Best Case Scenario",
    "Plan B Is Hope",
    "Nothing Can Go Wrong",
    "Surely This Time",
    "One More Sprint",
    "Next Sprint Will Fix It",
    "We’ll Get There",
    "Forward With Confidence",
    "Confidence Without Evidence",
    "Premature Success",
    "Unvalidated Hope",
    "Optimistically Incorrect",
    "Statistically Encouraging",
    "A Reasonable Amount of Hope",
    "Hope in Production",
    "Hope and Rollback",
    "Release With Confidence",
    "Confidence Is a Feature",
    "Hope Is Not a Strategy",
    "Strategy Is Still Loading",
    "The Plan Remains the Plan",
    "Plan Adjacent",
    "Outcome Pending",
    "Awaiting Good News",
    "Good News Expected",
    "Positive Developments Pending"
  ]},

  { id:"brainrot", label:"Gen Z Brainrot", accent:"#B8007E", names:[
    "Trigger Warning: Story Points",
    "POV: We Actually Finish This",
    "Delulu Is the Solulu",
    "No Cap, Just Bugs",
    "Copium Driven Development",
    "It’s Giving Technical Debt",
    "Main Character Deployment",
    "Lowkey Production Ready",
    "Highkey Not Tested",
    "Let Him Cook",
    "We’re So Back",
    "Never Been More Joever",
    "Chat, Are We Cooked?",
    "Chat, We’re So Back",
    "Bro Thought It Was Agile",
    "Skill Issue: Requirements",
    "Absolute Unit of Scope",
    "Aura Farming: Sprint Edition",
    "Negative Aura Deployment",
    "+100 Aura, −100 Tests",
    "No Thoughts, Just Tickets",
    "Vibes-Based Engineering",
    "Based on Absolutely Nothing",
    "Trust Me Bro",
    "Source: Jira",
    "Canon Event: Production Bug",
    "Lore Accurate Technical Debt",
    "Plot Armor Deployment",
    "The Sprint Has Aura",
    "Unspoken Rizz Requirements",
    "Requirements? I Barely Know Her",
    "Yap Until Green",
    "Yapping Is Grooming",
    "Cooked by Refinement",
    "Let Him Merge",
    "Merge Aura Check",
    "Git Push and Pray",
    "Deploy and Manifest",
    "Manifesting a Green Pipeline",
    "Manifesting No Rollback",
    "Manifestation > Estimation",
    "Delulu Planning Session",
    "Certified Copium Sprint",
    "Premium Copium",
    "Enterprise Grade Copium",
    "Copium as a Service",
    "Hopepilled",
    "Optimismpilled",
    "Sprintpilled",
    "Agilepilled",
    "Kanbanmaxxing",
    "Productivitymaxxing",
    "Technical Debtmaxxing",
    "Stakeholdermaxxing",
    "Refactormaxxing",
    "We Ball",
    "We Ship",
    "We Pray",
    "We Ball, Then Rollback",
    "No QA, We Ball",
    "YOLO Driven Development",
    "YOLO but Enterprise",
    "Skill Issue, Scalable",
    "This Is Fine, Unironically",
    "Everything Is a Feature Now",
    "It’s Giving Incident",
    "It’s Giving Rollback",
    "It’s Giving Hotfix",
    "It’s Giving 500",
    "Serving Production Issues",
    "Serving Stakeholder Delight",
    "Ate and Left No Tests",
    "No Crumbs, Only Regressions",
    "Slay the Sprint",
    "Slay Now, Debug Later",
    "Girlboss the Codebase",
    "Gaslight, Gatekeep, Git Push",
    "Gaslight the Acceptance Criteria",
    "Gatekeep the API",
    "Girlboss the Production Incident",
    "POV: The Estimate Was Binding",
    "POV: QA Found Nothing",
    "POV: It Passed Locally",
    "POV: Friday Deployment",
    "POV: The Rollback Is the Plan",
    "POV: Stakeholders Are Happy",
    "POV: Nothing Is on Fire",
    "POV: We Learned From Last Sprint",
    "POV: This Time Is Different"
  ]},

  { id:"bofh", label:"BOFH Excuses", accent:"#8A6B12", names:[
    "Root Dried Out",
    "Woodworms in Hashtable",
    "Quantum Packet Loss",
    "Cache Fermented",
    "DNS Went Stale",
    "Kernel Got Damp",
    "RAM Became Sentient",
    "Ethernet Is Molting",
    "Packets Got Lost Indoors",
    "Database Grew Roots",
    "TCP Lost Interest",
    "Hash Collision Outbreak",
    "Bitrot in Staging",
    "Socket Became Philosophical",
    "Compiler Is Sulking",
    "CPU Has Trust Issues",
    "Cache Reached Critical Mass",
    "Garbage Collector Unionized",
    "Threads Crossed Realities",
    "Semaphore Lost Custody",
    "Race Condition Won",
    "Mutex Became Jealous",
    "Deadlock Became Permanent",
    "Stack Overflowed Emotionally",
    "Heap Developed Mold",
    "Pointer Wandered Off",
    "Null Pointer Escaped",
    "Memory Leaked Into Production",
    "JIT Went Feral",
    "Bytecode Got Wet",
    "Source Code Condensed",
    "Git Repository Decomposed",
    "Branch Became Feral",
    "Merge Conflict Metastasized",
    "Commit Lost Structural Integrity",
    "Git History Became Sentient",
    "Remote Repository Migrated",
    "HEAD Detached Itself",
    "Repository Developed Termites",
    "CI Pipeline Achieved Escape Velocity",
    "Build Server Is Haunted",
    "Jenkins Entered Hibernation",
    "Pipeline Lost Atmospheric Pressure",
    "Docker Container Became Aquatic",
    "Container Breached Containment",
    "Kubernetes Lost the Plot",
    "Pod Achieved Independence",
    "Service Discovered Recursion",
    "Microservice Became Macroservice",
    "API Has Seasonal Allergies",
    "Endpoint Migrated Spontaneously",
    "Load Balancer Developed Bias",
    "Reverse Proxy Reversed Too Far",
    "HTTP Became Emotional",
    "TLS Certificate Lost Confidence",
    "OAuth Token Expired Spiritually",
    "JWT Became Non-Euclidean",
    "Session Wandered Off",
    "Cookie Developed Trust Issues",
    "Browser Cache Fossilized",
    "Frontend Entered Legacy Mode",
    "CSS Became Load-Bearing",
    "JavaScript Escaped Containment",
    "TypeScript Detected Negativity",
    "React Component Achieved Sentience",
    "npm Dependency Evolved",
    "Package Manager Became Recursive",
    "node_modules Reached Critical Density",
    "Webpack Summoned Something",
    "Regex Became Self-Aware",
    "JSON Became Structurally Ambiguous",
    "XML Closed Incorrectly",
    "YAML Indentation Drift",
    "Whitespace Instability Detected",
    "Unicode Escaped",
    "UTF-8 Lost Its Accent",
    "Encoding Became Sentient",
    "Cosmic Build Failure"
  ]},

  { id:"cult", label:"Corporate Cult", accent:"#14566B", names:[
    "Welcome to the Process",
    "Trust the Framework",
    "The Framework Knows",
    "Velocity Is Watching",
    "The Ceremony Begins at 09:00",
    "We Are All Product Owners Now",
    "You Have Been Selected for Refinement",
    "The Backlog Provides",
    "Do Not Question the Roadmap",
    "The Roadmap Is Eternal",
    "Your Sprint Belongs to the Team",
    "Compliance Is Enlightenment",
    "Attendance Is Mandatory",
    "The Board Sees All",
    "Alignment Is Peace",
    "Deviation Has Been Logged",
    "The Process Is the Product",
    "Sprint Zero Never Ended",
    "Your Capacity Has Been Assigned",
    "Resistance Is a Blocker",
    "The Velocity Must Rise",
    "Report to Refinement",
    "We Do Not Question Estimates",
    "The Ceremony Cannot Be Skipped",
    "All Praise the Burndown",
    "Your Story Points Are Noted",
    "The Framework Has No Exceptions"
  ]},

  { id:"occult", label:"Occult Scrum", accent:"#6A2E7A", names:[
    "The Sprint That Must Not Be Named",
    "Summoning the Definition of Done",
    "Ritual of the Missing Requirement",
    "The Forbidden Backlog",
    "Blood Pact With Production",
    "The Ancient Ticket Awakens",
    "Invoke the Hotfix",
    "The Stakeholder Has Foreseen It",
    "Seven Sprints of Darkness",
    "The Pipeline Demands a Sacrifice",
    "Heroku Exorcism",
    "The Merge Beyond the Veil",
    "As the Prophecy Predicted",
    "Do Not Merge After Midnight",
    "The Standup Has No End",
    "Nine Voices, One Estimate",
    "The Sprint Goal Chose Us",
    "Something Is in the Backlog",
    "The Retro Remembers",
    "It Knows Your Velocity",
    "The Board Moves Itself",
    "Do Not Name the Sprint",
    "The Ticket Was Always There",
    "Refinement Under a New Moon",
    "The Committee Beneath the Floor",
    "Whispers in the Changelog",
    "We Have Always Been Sprinting",
    "The Scrum Master Has No Reflection",
    "Consecrated Story Points",
    "The Burndown Never Reaches Zero",
    "Speak Not of the Velocity",
    "It Estimated Itself",
    "Something Groomed the Backlog",
    "The Daily Never Ended",
    "We Do Not Speak of Sprint 13",
    "The Velocity Wants More",
    "The Backlog Grows in Darkness",
    "Nothing Was Committed. Something Was.",
    "The Definition of Done Is Watching",
    "It Was Already in the Repository",
    "Daemons"
  ]},

  { id:"catastrophe", label:"Catastrophe Theatre", accent:"#A8480F", names:[
    "Runtime Error Manifesto",
    "Captain Segfault’s Disappointment",
    "Garbage Collector of Souls",
    "The Nullpointer Crusade",
    "Deadlock Symphony No. 5",
    "We Tried Nothing and We’re Out of Ideas",
    "Powered by Despair and Coffee",
    "Sprint of Utter Organizational Breakdown",
    "The KPI Funeral Parade",
    "Management Will Hate This One",
    "The Quantum Panic Express",
    "Lord of the Failing Unit Tests",
    "Galactic Deployment Meltdown",
    "Starship Oh God Not Again",
    "Planet of the Lost Requirements",
    "You Won’t Like the Burndown Chart",
    "Abandon Hope All Who Merge Here",
    "This Sprint Was a Mistake",
    "Bugs? More Like Features With Trauma",
    "Seriously Who Approved This Plan",
    "The Fellowship of Misaligned Estimates",
    "Scrum but Actually Chaos",
    "Merge Conflict Kindergarten",
    "Code Review Crying Circle",
    "The Overengineered Disaster Brigade"
  ]},

  { id:"unclassified", label:"Unclassified", accent:"#4A4D42", names:[
    "Chicken-Based Architecture",
    "Scrum but Everyone Is a Horse",
    "Tuesday Has Been Deprecated",
    "Banana Driven Development",
    "The Database Is Feeling Unwell",
    "Agile Goblin Mode",
    "Quantum Scrum",
    "Emotional Support Microservice",
    "Certified Bug Enjoyer",
    "Runtime Is a Social Construct",
    "Jira Ate My Homework",
    "We Forgot the WiFi",
    "PostgreSQL Has Entered the Chat",
    "The Build Has Opinions",
    "Kevin From Accounting Is the Load Balancer",
    "Seven Goblins, One Sprint",
    "The API Is Haunted",
    "Please Do Not Perceive the Code",
    "Please Do Not the Code",
    "Software Occurs",
    "This Sprint Is Legally a Suggestion"
  ]}
];
