/* ------------------------------------------------------------------
   THE CORPUS — this is the product. Everything else is packaging.

   Each genre also carries `exhausted`: the line the office prints once
   every name in the genre has been issued. It is written per genre
   rather than assembled from the label, because the joke has to land in
   that genre's own voice. build.js refuses to build without one.
------------------------------------------------------------------ */
const GENRES = [
  { id:"enterprise", label:"Enterprise Sarcasm", accent:"#A61F2B",
    exhausted:"You have exhausted Enterprise Sarcasm. The vocabulary, not the practice.",
    names:[
    "Refactor and Pray",
    "Tactical Optimism",
    "Ship Happens",
    "Escalation Is a Feature",
    "Merge With Caution",
    "Agile-ish",
    "Retrospective Regret",
    "Plausible Deniability",
    "Overengineered for Safety",
    "Per My Last Email",
    "Re: Per My Last Email",
    "Stakeholder Delight",
    "Selective Transparency",
    "Cache Me Outside",
    "Ship It Anyway",
    "Optimistic Rollback",
    "Minimal Viable Apology",
    "Enterprise Grade Anxiety",
    "Refinement by Fire",
    "Unintended Consequences",
    "Human Interface Problem",
    "Scope Drift Initiative",
    "Hotfix Horizon",
    "Silent Breaking Change",
    "Rollback Ready",
    "Minor Major Release",
    "Soft Deadline",
    "Future Technical Debt",
    "Spec Drift",
    "Incident Driven Dev",
    "Untested Confidence",
    "Courageous Refactor",
    "Blameless Postmortem",
    "Architectural Regret",
    "Deadline Negotiation Phase",
    "Definition of “Done-ish”",
    "High Risk No Reward",
    "Just One More Thing",
    "Regression Roulette",
    "Release and Regret",
    "Unverified Assumptions",
    "Elegant Workaround",
    "Feature Creep Diplomacy",
    "Strategic Reprioritization",
    "Deadline Is a Suggestion",
    "Backward Compatibility Theater",
    "Continuous Partial Delivery",
    "Legacy of Tomorrow",
    "Technical Debt Jubilee",
    "Ship First, Document Never",
    "Slightly Deterministic",
    "Chaos Driven Development",
    "Bug Driven Development",
    "Roadmap to Nowhere",
    "Sustainable Panic",
    "Test in Prod",
    "Compliance Adjacent",
    "Fail Forward Aggressively",
    "Stakeholder Alignment Ritual",
    "Soft Launch Into Darkness",
    "Beta Is the New Stable",
    "Zero Downtime (Mostly)",
    "Mission Critical-ish",
    "Cloud Native Denial",
    "Scalable Confusion",
    "Automated Blame Pipeline",
    "Governance Theater",
    "Architecture Astronautics",
    "Incremental Catastrophe",
    "Proactive Damage Control",
    "Every User Has a Test System"
  ]},
   
  { id:"despair", label:"Developer Despair", accent:"#1F4E9C",
    exhausted:"The despair is endless. The names for it are not.",
    names:[
    "Works on My Machine",
    "Git Blame the Other Guy",
    "Not My Branch",
    "Works in Production",
    "Probably Not My Bug",
    "Wasn’t Me",
    "Ask the Previous Developer",
    "It Was Like That Already",
    "I Inherited This",
    "Who Wrote This?",
    "Future Me’s Problem",
    "Not Enough Context",
    "Cannot Reproduce",
    "It Worked In Staging",
    "Just Don’t Touch It",
    "Do Not Refactor",
    "Please Don’t Look",
    "It’s Probably Caching",
    "Must Be DNS",
    "You’re Sure It’s not DNS?",
    "Must Be a Race Condition",
    "Legacy by Choice",
    "Technical Debt Enjoyer",
    "Tech Debt Is Due",
    "Borrowed Time",
    "Held Together by Hope",
    "Comments Are the Documentation",
    "Documentation Is Somewhere",
    "README was Lying",
    "The Tests Know Too Much",
    "Tests Are Optional",
    "CI Said Maybe",
    "Green Enough",
    "Pipeline Roulette",
    "Merge and Find Out",
    "Push First, Understand Later",
    "Commit and Forget",
    "Revert and Pretend",
    "Git Revert My Life",
    "Git Reset My Expectations",
    "Force Push of Despair",
    "Branching Out of Control",
    "Detached From Reality",
    "Lost in Git History",
    "Commit Archaeology",
    "Blame Driven Development",
    "Debugging by Astrology",
    "Stack Overflow Archaeology",
    "Copy Paste Engineering",
    "Cargo Cult Coding",
    "Trial and Error™",
    "Error and More Error",
    "Exceptionally Unclear",
    "Null and Void",
    "Undefined Behavior, Defined Lifestyle",
    "Concurrency Is a Social Problem",
    "The State Is Complicated",
    "State Management Crisis",
    "One More If",
    "Just One More Flag",
    "Just One More Bitmap",
    "Temporary Permanent Fix",
    "Permanent Temporary Fix",
    "Quick Fix, Long Term Consequences",
    "Five Minute Refactor",
    "Small Change™",
    "Tiny Little Hotfix",
    "Harmless Change",
    "Mostly Harmless",
    "Nothing Could Go Wrong",
    "We’ll Understand It Later",
    "Future Us Can Deal With It",
    "Past Me Was an Idiot",
    "Past Me Did This",
    "Past Me Had Reasons",
    "Future Me Hates This",
    "Somebody Approved This",
    "Someone Signed Off",
    "It Passed Review",
    "LGTM",
    "Approved Under Duress",
    "Peer Reviewed, Allegedly",
    "Tested in Spirit",
    "QA Has Been Notified",
    "Waiting for Reproduction",
    "Waiting for Godot.js",
    "QA Has Feedback",
    "Users Are the Test Suite",
    "Customer Driven Debugging",
    "Live Debugging Experience",
    "Monday Morning Rollback",
    "Deploy First, Panic Later",
    "Git History Repeats Itself"
  ]},

  { id:"oncall", label:"On-Call Horror", accent:"#33307A",
    exhausted:"The register sleeps. You do not.",
    names:[
    "Three AM Deployment",
    "Escalation Pending",
    "Wake Up, It’s Prod",
    "Who Has the Phone",
    "Weekend Incident",
    "Production Needs You",
    "On Call, On Sight",
    "Rotating the Suffering",
    "Severity: Weekend",
    "Blast Radius: Bedroom",
    "Five Nines, Zero Sleep",
    "Uptime at Any Cost",
    "Availability Has a Price",
    "SLA Versus REM",
    "Production Called",
    "Production Calls Again",
    "Production Has Your Number",
    "Production Knows Where You Sleep",
    "Weekend Availability Event",
    "Pinged by DevOps",
    "Not My Oncall Duty",
    "Pager Duty Jump Scare",
    "Friday Deploy Survivor"
  ]},

  { id:"hope", label:"Hope Driven Dev", accent:"#1E6B4F",
    exhausted:"All hope allocated. Confidence remains high.",
    names:[
    "Optimism Under Review",
    "Hope Driven Development",
    "Confidence Pending",
    "Probably Fine",
    "Trust the Process",
    "Faith Based Deployment",
    "Strategic Optimism",
    "Hope as a Strategy",
    "Deferred Optimism",
    "Tentative Success",
    "Fingers Crossed",
    "Managed Expectations",
    "Controlled Optimism",
    "Hopeful Regression",
    "Confidence in Progress",
    "Promisingly Unstable",
    "Potentially Fine",
    "Eventually Correct",
    "Progress, Allegedly",
    "Almost Certain",
    "Low Confidence, High Hopes",
    "Operational Optimism",
    "Hopeful but Unverified",
    "Expected to Work",
    "Probability of Success",
    "Best Case Scenario",
    "Plan B Is Hope",
    "Nothing Can Go Wrong",
    "Surely This Time",
    "One More Sprint",
    "The Next Sprint Will Fix It",
    "We’ll Get There",
    "Forward With Confidence",
    "Confidence Without Evidence",
    "Premature Success",
    "Unvalidated Hope",
    "Optimistically Incorrect",
    "Statistically Encouraging",
    "A Reasonable Amount of Hope",
    "Hope Based Prod Deployment",
    "Release With Confidence",
    "Confidence Is Key",
    "Plan Adjacent",
    "Outcome Pending",
    "Positive Developments Pending",
    "Please Do Not the Code",
  ]},

  { id:"brainrot", label:"Gen Z Brainrot", accent:"#B8007E",
    exhausted:"Zero names left, based and scrumpilled.",
    names:[
    "Trigger Warning: Story Points",
    "Agile Goblin Mode",
    "POV: We Actually Finish This",
    "Delulu Is the Solulu",
    "No Cap, Just Bugs",
    "Copium Driven Development",
    "It’s Giving Technical Debt",
    "Main Character Deployment",
    "Lowkey Production Ready",
    "Highkey Not Tested",
    "Let Him Cook",
    "Who Let Him Cook?",
    "Never Cook again",
    "We’re So Back",
    "Never Been More Joever",
    "Chat, Are We Cooked?",
    "Chat, We’re So Back",
    "Bro Thought It Was Agile",
    "Skill Issue: Requirements",
    "Absolute Unit of Scope",
    "Aura Farming: Sprint Edition",
    "Negative Aura Deployment",
    "Aura Based Deployment",
    "+100 Aura, 0 Tests",
    "No Thoughts, Just Tickets",
    "Vibes-Based Engineering",
    "Based on Absolutely Nothing",
    "Trust Me Bro",
    "Source: Jira",
    "Canon Event: Production Bug",
    "Lore Accurate Technical Debt",
    "Plot Armor Deployment",
    "The Sprint Lacks Aura",
    "Unspoken Rizz Requirements",
    "Requirements? I Barely Know Her",
    "Yap Until Green",
    "Yapping In The Review Comments",
    "Cooked by Refinement",
    "Let Him Merge",
    "Git Push and Pray",
    "Deploy and Manifest",
    "Manifesting a Green Pipeline",
    "Manifesting No Rollback",
    "Manifestation > Estimation",
    "Delulu Planning Session",
    "Certified Copium Sprint",
    "Premium Copium",
    "Enterprise Grade Copium",
    "Copium as a Service",
    "Hopepilled",
    "Optimismpilled",
    "Sprintpilled",
    "Agilepilled",
    "Kanbanmaxxing",
    "Agilemaxxing",
    "Productivitymaxxing",
    "Techdebtmaxxing",
    "Stakeholdermaxxing",
    "Refactormaxxing",
    "We Ship",
    "We Pray",
    "No QA, We Ball",
    "YOLO Driven Development",
    "Skill Issue, Scalable",
    "It’s Giving Incident",
    "It’s Giving Rollback",
    "It’s Giving 500",
    "Slay Now, Debug Later",
    "Gaslight, Gatekeep, Git Push",
    "Gaslight the Acceptance Criteria",
    "POV: The Estimate Was Binding",
    "POV: QA Found Nothing",
    "POV: Friday Deployment",
    "POV: We Learned From Last Sprint",
    "POV: This Time Is Different",
    "Vibe-Based Architecture"
  ]},

  { id:"bofh", label:"BOFH Excuses", accent:"#8A6B12",
    exhausted:"No excuses remain. Try telling them the truth.",
    names:[
    "Root Dried Out",
    "Woodworms in Hashtable",
    "Cache Fermented",
    "Cookies Went Stale",
    "Kernel Got Damp",
    "RAM Became Sentient",
    "Packets Got Lost",
    "Database Grew Roots",
    "TCP Lost Interest",
    "Hash Collision Outbreak",
    "Bitrot in Staging",
    "Compiler Is Sulking",
    "Trust Store Has Trust Issues",
    "Garbage Collector Unionized",
    "Semaphore Lost Custody",
    "Race Condition Won",
    "Mutex Became Jealous",
    "Deadlock Became Permanent",
    "Stack Overflowed Emotionally",
    "Heap Developed Mold",
    "Pointer Wandered Off",
    "Null Pointer Escaped",
    "Bytecode Got Wet",
    "Source Code Condensed",
    "Git Repository Decomposed",
    "Branch Became Feral",
    "Merge Conflict Metastasized",
    "Commit Lost Structural Integrity",
    "Remote Repository Migrated",
    "HEAD Detached Itself",
    "Repository Developed Termites",
    "CI Pipeline Achieved Escape Velocity",
    "Build Server Is Haunted",
    "Stubborn Processes",
    "Pipeline Lost Pressure",
    "Pipeline Started Leaking",
    "Ether Leak",
    "Kubernetes Lost the Plot",
    "Microservice Became Macroservice",
    "API Has Seasonal Allergies",
    "Endpoint Migrated Spontaneously",
    "Load Balancer Developed Bias",
    "Reverse Proxy Reversed Too Far",
    "TLS Certificate Lost Confidence",
    "OAuth Token Expired Spiritually",
    "Session Wandered Off",
    "Browser Cache Fossilized",
    "Frontend Entered Legacy Mode",
    "CSS Became Load-Bearing",
    "npm Dependency Evolved",
    "node_modules Reached Critical Density",
    "Webpack Summoned Something",
    "Regex Became Self-Aware",
    "YAML Indentation Drift",
    "Whitespace Instability Detected",
    "Unicode Escaped",
    "Backbone Collapsed",
    "Solar Flares",
    "Cosmic Build Failure",
    "Daemons"
  ]},

  { id:"cult", label:"Corporate Cult", accent:"#14566B",
    exhausted:"There are no names left. Attendance is still mandatory.",
    names:[
    "Welcome to the Process",
    "Trust the Framework",
    "The Framework Knows",
    "Velocity Is Watching",
    "The Ceremony Begins at 09:00",
    "Your Feedback Is Valuable",
    "You Have Been Selected for Refinement",
    "The Backlog Provides",
    "Do Not Question the Roadmap",
    "The Roadmap Is Eternal",
    "Scrum Master Sacrifice",
    "Compliance Is Enlightenment",
    "Attendance Is Mandatory",
    "The Board Sees All",
    "Alignment Is Peace",
    "Deviation Has Been Logged",
    "The Scope Is Sacred",
    "Sprint Zero Never Ended",
    "Your Capacity Has Been Assigned",
    "Resistance Is a Blocker",
    "The Velocity Must Rise",
    "We Do Not Question Estimates",
    "The Ceremony Cannot Be Skipped",
    "All Praise the Burndown",
    "The Sprint Will Continue Without You",
    "The Burndown Shall Judge Us",
    "Blessed Are The Aligned",
    "May The Framework Have Mercy"
  ]},

  { id:"occult", label:"Occult Scrum", accent:"#6A2E7A",
    exhausted:"The register is empty. But something always lurks in the backlog.",
    names:[
    "Summoning the Definition of Done",
    "Ritual of the Missing Requirement",
    "The Forbidden Backlog",
    "Blood Pact With Production",
    "The Ancient Ticket Awakens",
    "Invoke the Hotfix",
    "The Stakeholder Has Foreseen It",
    "Seven Sprints of Darkness",
    "The Pipeline Demands a Sacrifice",
    "Heroku Exorcism",
    "KPI Exorcism",
    "The Merge Beyond the Veil",
    "As the Prophecy Predicted",
    "Do Not Merge After Midnight",
    "The Standup Has No End",
    "Nine Voices, One Estimate",
    "The Sprint Goal Chose Us",
    "Something Is in the Backlog",
    "The Retro Remembers",
    "It Knows Your Velocity",
    "Do Not Name the Sprint",
    "The Ticket Was Always There",
    "Whispers in the Changelog",
    "We Have Always Been Sprinting",
    "The Scrum Master Has No Reflection",
    "Consecrated Story Points",
    "The Burndown Never Reaches Zero",
    "Speak Not of the Velocity",
    "It Estimated Itself",
    "Something Groomed the Backlog",
    "The Daily Never Ended",
    "We Do Not Speak of Sprint 13",
    "The Velocity Wants More",
    "The Backlog Grows in Darkness",
    "Nothing Was Committed. Something Was.",
  ]},

  { id:"catastrophe", label:"Catastrophe Theatre", accent:"#A8480F",
    exhausted:"Nothing left to name. The catastrophe proceeds unlabelled.",
    names:[
    "Runtime Error Manifesto",
    "Captain Segfault’s Disappointment",
    "Garbage Collector of Souls",
    "The Nullpointer Crusade",
    "Deadlock Symphony No. 5",
    "We Tried Nothing and We’re Out of Ideas",
    "Powered by Despair and Coffee",
    "Sprint of Utter Organizational Breakdown",
    "The KPI Funeral Parade",
    "Management Will Hate This One",
    "You Won’t Like the Burndown Chart",
    "This Sprint Was a Mistake",
    "Seriously Who Approved This Plan",
    "Scrum but Actually Chaos",
    "Code Review Crying Circle",
  ]},
];
